### ISSUE TITLE
Will this work for RK84?

### ISSUE THREAD

**Issue by petereon** [oddlyspaced/rkcu#1]
Hi, I apologize for potentially dumb question. But will this work for RK84 apart from having to change the obvious `product id` and potentially `vendor id`?

Is there anything I can painfully mess up on the keyboard by trying it?

**Comment by oddlyspaced** [comment]
I'm mostly sure that this would work for the RK84. The configuration packets are very generalized from what I noticed when digging through the implementation. Plus I don't think you can mess up anything since the onboard firmware rejects the packet if it is not able to parse the parameters.

Do let me know if you try the script or need regarding anything,

**Comment by oddlyspaced** [comment]
closing this, please open a new issue in case you have any queries.
